project_name/example_app/urls.py
from django.conf.urls import patterns, url
from example_app.views import sample_view, accounts

urlpatterns = patterns('',
                       url(r'^$', sample_view.index, name='index'),
                       url(r'post/', sample_view.post, name='post'),
                       url(r'login/', accounts.signin, name='signin'),
                       url(r'logout/', accounts.signout, name='signout'),
                       )

project_name/project_name/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
                       url(r'', include('example_app.urls')),
    # Examples:
    # url(r'^$', 'project_name.views.home', name='home'),
    # url(r'^project_name/', include('project_name.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

project_name/example_app/models/post_message.py
from django.db import models
from django.utils import timezone


class PostMessage(models.Model):
    name = models.CharField(max_length=15)
    message = models.TextField()
    upload_file = models.TextField()
    post_date = models.DateTimeField(default=timezone.now)

    class Meta:
        app_label = 'example_app'

project_name/example_app/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=15)
    password = forms.CharField(max_length=15, widget=forms.PasswordInput)


class PostMessageForm(forms.Form):
    name = forms.CharField(max_length=15, required=False)
    message = forms.CharField(widget=forms.widgets.Textarea())
    upload_file = forms.FileField(required=False)

project_name/example_app/views/accounts.py
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response
from example_app import forms
from example_app.views.decorator import login_checker


@csrf_protect
def signin(request):
    if request.user.is_authenticated():
        next_url = request.GET.get('next', '/')
        return HttpResponseRedirect(next_url)

    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(request.POST.get('next', '/'))

                else:
                    login_form = forms.LoginForm()
                    return render_to_response('example_app/login.html',
                                              {'login_form': login_form,
                                               'next': request.POST.get('next'),
                                               'account_status': 'inactive'},
                                              context_instance=RequestContext(request))

            else:
                login_form = forms.LoginForm()
                return render_to_response('example_app/login.html',
                                          {'login_form': login_form,
                                           'next': request.POST.get('next'),
                                           'account_status': 'invalid'},
                                          context_instance=RequestContext(request))
        else:
            login_form = forms.LoginForm()
            return render_to_response('example_app/login.html',
                                      {'login_form': login_form,
                                       'account_status': 'nologin'},
                                      context_instance=RequestContext(request))


@login_checker
def signout(request):
    logout(request)
    return HttpResponseRedirect('/')

project_name/example_app/views/decorator.py
from django.template import RequestContext
from django.shortcuts import render_to_response
from example_app import forms


def login_checker(view_func):
    def wrap(request, *args, **kwargs):
        if not request.user.is_authenticated():
            login_form = forms.LoginForm()
            return render_to_response('example_app/login.html',
                                      {'login_form': login_form,
                                       'next': request.get_full_path(),
                                       'account_status': 'nologin'},
                                      context_instance=RequestContext(request))

        else:
            return view_func(request, *args, **kwargs)

    wrap.__doc__ = view_func.__doc__
    wrap.__name__ = view_func.__name__

    return wrap

project_name/example_app/views/sample_view.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from example_app.views.decorator import login_checker
from example_app import forms
from example_app.models.post_message import PostMessage


@login_checker
def index(request):
    post_message_form = forms.PostMessageForm()
    messageset = PostMessage.objects.all().order_by('-post_date')

    return render_to_response('example_app/index.html',
                              {'post_message_form': post_message_form,
                               'messageset': messageset},
                              context_instance=RequestContext(request))


@login_checker
def post(request):
    if request.method == 'POST':
        form = forms.PostMessageForm(request.POST, request.FILES)

        if form.is_valid():
            name = request.POST.get('name')
            message = request.POST.get('message')
            upload_file = request.FILES.get('upload_file', None)

            if not name:
                name = 'anonymous'

            if upload_file:
                content = upload_file.read()
            else:
                content = ''

            new_post = PostMessage(name=name, message=message, upload_file=content)
            new_post.save()

        return HttpResponseRedirect('/')

    else:
        raise Http404

project_name/templates/example_app/base.html
<!DOCTYPE html>
<meta charset="utf-8">

{% load staticfiles %}
<link rel="stylesheet" href="{% static "css/style.css" %}">

<title>
  {% block title %}
    example app
  {% endblock title %}
</title>

{% block content %}
{% endblock content %}

{% block footer %}
{% endblock footer %}

project_name/templates/example_app/index.html
{% extends "example_app/base.html" %}

{% block content %}
  <h1>GUESTBOOK</h1>

  {% block message %}
    {% if is_post %}
      <p> Submit successfully!</p>
    {% endif %}
  {% endblock message %}

  {% if post_message_form %}
    <form action="/post/" method="post" enctype="multipart/form-data">{% csrf_token %}
      <div class="field_wrapper">
        <label for="id_name">Name</label>
        {{ post_message_form.name|safe }}
      </div>

      <div class="field_wrapper">
        <label for="id_message">Text</label><br>
        {{ post_message_form.message|safe }}
      </div>

      <div class="field_wrapper">
        <label for="id_message">Upload</label>
        {{ post_message_form.upload_file|safe }}
      </div>

      <div class="field_wrapper">
        <input type="submit", value="Submit">
      </div>
    </form>
  {% endif %}

  {% if messageset %}
    {% for m in messageset %}
      <br>
      <table>
        <tbody>
          <tr>
            <th>Name</th>
            <td>{{ m.name }}</td>
            <th>Date</th>
            <td>{{ m.post_date }}</td>
          </tr>
          <tr>
            <td colspan="4">{{ m.message }}</td>
          </tr>
        </tbody>
      </table>
      <br>
    {% endfor %}
  {% endif %}
{% endblock content %}

project_name/templates/example_app/login.html
{% extends "example_app/base.html" %}

{% block content %}
{% if login_form %}
  {% if account_status == 'nologin' %}
    <p>Welcome!</p>
  {% elif account_status == 'inactive' %}
    <p>Inactive user!</p>
  {% elif account_status == 'invalid' %}
    <p>Invalid user!</p>
  {% endif %}

  {# {% if login_form.errors %} #}
  {#   <p>Your username and password didn't match. Please try again.</p> #}
  {# {% endif %} #}

  <form action="/login/" method="post">{% csrf_token %}

    {# {{ login_form.non_field_errors|safe }} #}

    <div class="fieldWrapper">
      {{ login_form.username.errors }}
      <label for="id_username">User Name</label>
      {{ login_form.username|safe }}
    </div>

    <div class="fieldWrapper">
      {{ login_form.password.errors }}
      <label for="id_password">Password</label>
      {{ login_form.password|safe }}
    </div>

    <div class="fieldWrapper">
      <input type="submit" value="Login" />
      <input type="hidden" name="next" value={{ next }} />
    </div>
  </form>
{% endif %}
{% endblock content %}